// @generated by scripts/ci/generate_sdk_schema_models.py; DO NOT EDIT.
// Rust JSON Schema set SHA-256: 12900d249f6fb347d57e8f253d47b0fad816366575a7e7730a3bdc54beb38f62

export type UInt64 = number | bigint;

export type BenchmarkMode = "baseline" | "bounded";

export type CheckpointPolicy = "disabled" | "delete_on_success" | "retain_on_failure";

export type InputGeneratorV1 = ({ initial_a: UInt64; initial_b: UInt64; kind: "fibonacci"; }) | ({ kind: "poseidon2"; seed: UInt64; }) | ({ blake3_hex: string; kind: "digest"; });

export interface PhaseEstimateV1 {
  phase: string;
  read_bytes: UInt64;
  write_bytes: UInt64;
}

export interface ReleaseProvenanceV1 {
  dependency_profile: string;
  proof_serializer: string;
  prover_version: string;
  release_sha: string;
  verifier_version: string;
}

export interface ResourceEstimateV1 {
  peak_resident_bytes: UInt64;
  phases: Array<PhaseEstimateV1>;
  scratch_high_water_bytes: UInt64;
  total_read_bytes: UInt64;
  total_write_bytes: UInt64;
}

export type ResourceMode = "auto" | "memory" | "scratch";

export interface ResourcePolicyV1 {
  checkpoint_policy: CheckpointPolicy;
  max_resident_bytes: UInt64;
  max_scratch_bytes: UInt64;
  max_threads: number;
  mode: ResourceMode;
  scratch_dir: string;
}

export type WorkloadId = "fibonacci" | "poseidon2_goldilocks";

export interface WorkloadManifestV1 {
  backend: string;
  deterministic_seed: UInt64;
  expected_verifier: string;
  input_generator: InputGeneratorV1;
  logical_rows: UInt64;
  profile: string;
  resource_policy: ResourcePolicyV1;
  schema_version: number;
  workload_id: WorkloadId;
}

export interface ProofBundleV1 {
  manifest: WorkloadManifestV1;
  manifest_digest_hex: string;
  proof_base64url: string;
  proof_digest_hex: string;
  provenance: ReleaseProvenanceV1;
  public_values: Array<UInt64>;
  schema_version: number;
}

export interface BenchmarkReportV1 {
  benchmark_session_id: string;
  cgroup_peak_bytes: UInt64;
  cpu_seconds: number;
  dependency_profile: string;
  exact_command: Array<string>;
  exit_status: number;
  failure_diagnostic?: string | null;
  hardware: string;
  logical_cpu_count: number;
  mode: BenchmarkMode;
  normalized_manifest_digest_hex: string;
  normalized_manifest_path: string;
  operating_system: string;
  peak_rss_bytes: UInt64;
  preflight_estimate: ResourceEstimateV1;
  proof_size_bytes: UInt64;
  read_bytes: UInt64;
  release_sha: string;
  schema_version: number;
  scope: string;
  scratch_high_water_bytes: UInt64;
  storage: string;
  storage_device: string;
  storage_is_nvme: boolean;
  storage_is_rotational: boolean;
  total_memory_bytes: UInt64;
  verification_succeeded: boolean;
  verification_time_ms: UInt64;
  wall_time_ms: UInt64;
  workload_manifest_digest_hex: string;
  write_bytes: UInt64;
}
