// @generated by scripts/ci/generate_sdk_schema_models.py; DO NOT EDIT.
// Rust JSON Schema set SHA-256: 51c8c1110224f9249b1da38e22599dec3c8d0b5a2565c76e75f059ccccc9a67a

export type UInt64 = number | bigint;

export type AirConstraintKindV1 = "transition" | "first_row" | "last_row";

export interface AirConstraintV1 {
  expression: number;
  kind: AirConstraintKindV1;
}

export type AirExpressionV1 = ({ op: "constant"; value: UInt64; }) | ({ column: number; op: "current"; }) | ({ column: number; op: "next"; }) | ({ index: number; op: "public"; }) | ({ left: number; op: "add"; right: number; }) | ({ left: number; op: "sub"; right: number; }) | ({ left: number; op: "mul"; right: number; });

export interface AirPackageV1 {
  backend: string;
  constraints: Array<AirConstraintV1>;
  expected_verifier: string;
  expressions: Array<AirExpressionV1>;
  field: string;
  profile: string;
  public_inputs: Array<PublicInputSlotV1>;
  schema_version: number;
  trace_width: number;
}

export interface AirProofBundleV1 {
  air: AirPackageV1;
  air_digest_hex: string;
  proof_base64url: string;
  proof_digest_hex: string;
  provenance: ReleaseProvenanceV1;
  public_inputs: PublicInputsV1;
  public_inputs_digest_hex: string;
  schema_version: number;
  trace_manifest: TraceManifestV1;
  trace_manifest_digest_hex: string;
}

export type BenchmarkMode = "baseline" | "bounded";

export type CheckpointPolicy = "disabled" | "delete_on_success" | "retain_on_failure";

export interface HostedResourceReportV1 {
  peak_resident_bytes: UInt64;
  scratch_high_water_bytes: UInt64;
  total_read_bytes: UInt64;
  total_write_bytes: UInt64;
  wall_time_ms: UInt64;
}

export type InputGeneratorV1 = ({ initial_a: UInt64; initial_b: UInt64; kind: "fibonacci"; }) | ({ kind: "poseidon2"; seed: UInt64; }) | ({ blake3_hex: string; kind: "digest"; });

export interface PhaseEstimateV1 {
  phase: string;
  read_bytes: UInt64;
  write_bytes: UInt64;
}

export interface PublicInputSlotV1 {
  name: string;
}

export interface PublicInputsV1 {
  air_digest_hex: string;
  schema_version: number;
  values: Array<UInt64>;
}

export interface ReleaseProvenanceV1 {
  dependency_profile: string;
  proof_serializer: string;
  prover_version: string;
  release_sha: string;
  verifier_version: string;
}

export interface ResourceEstimateV1 {
  peak_resident_bytes: UInt64;
  phases: Array<PhaseEstimateV1>;
  scratch_high_water_bytes: UInt64;
  total_read_bytes: UInt64;
  total_write_bytes: UInt64;
}

export type ResourceMode = "auto" | "memory" | "scratch";

export interface ResourcePolicyV1 {
  checkpoint_policy: CheckpointPolicy;
  max_resident_bytes: UInt64;
  max_scratch_bytes: UInt64;
  max_threads: number;
  mode: ResourceMode;
  scratch_dir: string;
}

export interface TraceChunkV1 {
  blake3_hex: string;
  compressed_bytes: UInt64;
  index: number;
  uncompressed_bytes: UInt64;
}

export interface TraceManifestV1 {
  air_digest_hex: string;
  chunk_uncompressed_bytes: UInt64;
  chunks: Array<TraceChunkV1>;
  compression: string;
  field_encoding: string;
  logical_rows: UInt64;
  schema_version: number;
  trace_digest_hex: string;
  trace_width: number;
}

export type WorkloadId = "fibonacci" | "poseidon2_goldilocks";

export interface WorkloadManifestV1 {
  backend: string;
  deterministic_seed: UInt64;
  expected_verifier: string;
  input_generator: InputGeneratorV1;
  logical_rows: UInt64;
  profile: string;
  resource_policy: ResourcePolicyV1;
  schema_version: number;
  workload_id: WorkloadId;
}

export interface ProofBundleV1 {
  manifest: WorkloadManifestV1;
  manifest_digest_hex: string;
  proof_base64url: string;
  proof_digest_hex: string;
  provenance: ReleaseProvenanceV1;
  public_values: Array<UInt64>;
  schema_version: number;
}

export interface BenchmarkReportV1 {
  benchmark_session_id: string;
  cgroup_peak_bytes: UInt64;
  cpu_seconds: number;
  dependency_profile: string;
  exact_command: Array<string>;
  exit_status: number;
  failure_diagnostic?: string | null;
  hardware: string;
  logical_cpu_count: number;
  mode: BenchmarkMode;
  normalized_manifest_digest_hex: string;
  normalized_manifest_path: string;
  operating_system: string;
  peak_rss_bytes: UInt64;
  preflight_estimate: ResourceEstimateV1;
  proof_size_bytes: UInt64;
  read_bytes: UInt64;
  release_sha: string;
  schema_version: number;
  scope: string;
  scratch_directory_mode: number;
  scratch_high_water_bytes: UInt64;
  scratch_owned_by_runner: boolean;
  storage: string;
  storage_available_bytes: UInt64;
  storage_device: string;
  storage_is_nvme: boolean;
  storage_is_rotational: boolean;
  storage_total_bytes: UInt64;
  total_memory_bytes: UInt64;
  verification_succeeded: boolean;
  verification_time_ms: UInt64;
  wall_time_ms: UInt64;
  workload_manifest_digest_hex: string;
  write_bytes: UInt64;
}

export interface HostedProofBundleV1 {
  charge_millicredits: UInt64;
  official_verification: boolean;
  proof: AirProofBundleV1;
  resource_report: HostedResourceReportV1;
  schema_version: number;
}
