FROM rust:1.95-bookworm@sha256:6258907abe69656e41cd992e0b705cdcfabcbbe3db374f92ed2d47121282d4a1 AS build
ARG HC_RELEASE_SHA
ENV HC_RELEASE_SHA=$HC_RELEASE_SHA
WORKDIR /src
COPY . .
RUN cargo build --locked --release -p hc-cli

FROM scratch
COPY --from=build /src/target/release/hc-cli /hc-cli-linux-x86_64
