#!/usr/bin/env python3
"""Generate Python and TypeScript models from Rust-emitted JSON Schemas."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys


SCHEMA_FILES = (
    "workload-manifest-v1.schema.json",
    "proof-bundle-v1.schema.json",
    "benchmark-report-v1.schema.json",
)
MODEL_NAMES = {
    "PhaseEstimate": "PhaseEstimateV1",
    "ResourceEstimate": "ResourceEstimateV1",
}


def model_name(name: str) -> str:
    return MODEL_NAMES.get(name, name)


def load_contracts(schema_dir: Path) -> tuple[dict[str, dict], list[tuple[str, dict]], str]:
    definitions: dict[str, dict] = {}
    roots: list[tuple[str, dict]] = []
    digest = hashlib.sha256()
    for filename in SCHEMA_FILES:
        path = schema_dir / filename
        raw = path.read_bytes()
        digest.update(filename.encode())
        digest.update(b"\0")
        digest.update(raw)
        schema = json.loads(raw)
        title = schema.get("title")
        if not isinstance(title, str) or not title:
            raise ValueError(f"{filename} has no schema title")
        roots.append((title, schema))
        for name, definition in schema.get("$defs", {}).items():
            existing = definitions.get(name)
            if existing is not None and existing != definition:
                raise ValueError(f"conflicting schema definition: {name}")
            definitions[name] = definition
    return definitions, roots, digest.hexdigest()


def ref_name(schema: dict) -> str | None:
    reference = schema.get("$ref")
    if not isinstance(reference, str):
        return None
    prefix = "#/$defs/"
    if not reference.startswith(prefix):
        raise ValueError(f"unsupported schema reference: {reference}")
    return model_name(reference.removeprefix(prefix))


def ts_type(schema: dict) -> str:
    reference = ref_name(schema)
    if reference:
        return reference
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "oneOf" in schema:
        return " | ".join(f"({ts_type(option)})" for option in schema["oneOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts_primitive(value, schema) for value in kind)
    if kind == "object":
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        fields = [
            f"{name}{'' if name in required else '?'}: {ts_type(value)};"
            for name, value in properties.items()
        ]
        return "{ " + " ".join(fields) + " }"
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    return ts_primitive(kind, schema)


def ts_primitive(kind: object, schema: dict) -> str:
    if kind == "integer" and schema.get("format") == "uint64":
        return "UInt64"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def ts_named(name: str, schema: dict) -> str:
    name = model_name(name)
    if schema.get("type") == "object":
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        lines = [f"export interface {name} {{"]
        for field, value in properties.items():
            optional = "" if field in required else "?"
            lines.append(f"  {field}{optional}: {ts_type(value)};")
        lines.append("}")
        return "\n".join(lines)
    return f"export type {name} = {ts_type(schema)};"


def render_typescript(definitions: dict[str, dict], roots: list[tuple[str, dict]], digest: str) -> str:
    blocks = [
        "// @generated by scripts/ci/generate_sdk_schema_models.py; DO NOT EDIT.",
        f"// Rust JSON Schema set SHA-256: {digest}",
        "",
        "export type UInt64 = number | bigint;",
        "",
    ]
    for name in sorted(definitions):
        blocks.extend((ts_named(name, definitions[name]), ""))
    for name, schema in roots:
        if name not in definitions:
            blocks.extend((ts_named(name, schema), ""))
    return "\n".join(blocks).rstrip() + "\n"


def python_type(schema: dict) -> str:
    reference = ref_name(schema)
    if reference:
        return f"{reference}Model"
    if "const" in schema:
        return f"Literal[{schema['const']!r}]"
    if "enum" in schema:
        return "Literal[" + ", ".join(repr(value) for value in schema["enum"]) + "]"
    kind = schema.get("type")
    if isinstance(kind, list):
        return "Union[" + ", ".join(python_primitive(value) for value in kind) + "]"
    if kind == "array":
        return f"list[{python_type(schema.get('items', {}))}]"
    return python_primitive(kind)


def python_primitive(kind: object) -> str:
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "null": "None",
    }.get(kind, "Any")


def pascal(value: object, fallback: str) -> str:
    if isinstance(value, str):
        result = "".join(part.capitalize() for part in re.split(r"[^A-Za-z0-9]+", value) if part)
        if result:
            return result
    return fallback


def python_typed_dict(name: str, schema: dict) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    optional = [field for field in properties if field not in required]
    required_fields = [field for field in properties if field in required]
    lines: list[str] = []
    base = name
    if optional and required_fields:
        base = f"_{name}Required"
        lines.append(f"class {base}(TypedDict):")
        lines.extend(f"    {field}: {python_type(properties[field])}" for field in required_fields)
        lines.append("")
        lines.append(f"class {name}({base}, total=False):")
        lines.extend(f"    {field}: {python_type(properties[field])}" for field in optional)
    else:
        total = ", total=False" if optional else ""
        lines.append(f"class {name}(TypedDict{total}):")
        fields = optional if optional else required_fields
        lines.extend(f"    {field}: {python_type(properties[field])}" for field in fields)
    if lines[-1].endswith(":"):
        lines.append("    pass")
    return "\n".join(lines)


def python_named(name: str, schema: dict) -> str:
    output_name = f"{model_name(name)}Model"
    if schema.get("type") == "object":
        return python_typed_dict(output_name, schema)
    if "oneOf" in schema:
        variants: list[str] = []
        blocks: list[str] = []
        for index, option in enumerate(schema["oneOf"], start=1):
            discriminator = option.get("properties", {}).get("kind", {}).get("const")
            variant = f"{model_name(name)}{pascal(discriminator, f'Variant{index}')}Model"
            blocks.append(python_typed_dict(variant, option))
            variants.append(variant)
        blocks.append(f"{output_name} = Union[{', '.join(variants)}]")
        return "\n\n".join(blocks)
    return f"{output_name} = {python_type(schema)}"


def render_python(definitions: dict[str, dict], roots: list[tuple[str, dict]], digest: str) -> str:
    blocks = [
        '"""Generated schema models. Do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal, TypedDict, Union",
        "",
        f'RUST_SCHEMA_SET_SHA256 = "{digest}"',
        "",
    ]
    for name in sorted(definitions):
        blocks.extend((python_named(name, definitions[name]), ""))
    for name, schema in roots:
        if name not in definitions:
            blocks.extend((python_named(name, schema), ""))
    return "\n".join(blocks).rstrip() + "\n"


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            print(f"generated SDK model drift: {path}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)
    return True


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema-dir", type=Path, required=True)
    parser.add_argument("--python-output", type=Path, required=True)
    parser.add_argument("--typescript-output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        definitions, roots, digest = load_contracts(args.schema_dir)
        valid = write_or_check(
            args.python_output,
            render_python(definitions, roots, digest),
            args.check,
        )
        valid &= write_or_check(
            args.typescript_output,
            render_typescript(definitions, roots, digest),
            args.check,
        )
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"SDK model generation failed: {error}", file=sys.stderr)
        return 2
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
